import random

_TOPS = [
    ("Slim Fit V-neck T-shirt", "white", "H&M", "$12.99", "Lightweight cotton V-neck in slim fit. Perfect for layering or wearing solo."),
    ("Regular Fit Crew Neck Tee", "black", "H&M", "$9.99", "Essential crew neck in soft jersey cotton. Relaxed everyday silhouette."),
    ("Slim Fit Linen T-shirt", "ivory", "H&M", "$19.99", "Breathable linen-blend tee with a clean finish. Ideal for warm-weather styling."),
    ("Oversized Graphic Tee", "grey", "H&M", "$14.99", "Dropped-shoulder graphic tee with washed finish. Streetwear-ready silhouette."),
    ("Regular Fit Oxford Shirt", "light blue", "H&M", "$29.99", "Classic Oxford weave shirt with button-down collar. Versatile smart-casual piece."),
    ("Slim Fit Resort Shirt", "navy", "H&M", "$24.99", "Short-sleeve printed shirt in woven fabric. Perfect for resort and yacht occasions."),
    ("Ribbed Henley T-shirt", "beige", "H&M", "$16.99", "Soft ribbed henley with three-button placket. Adds texture to any outfit."),
    ("Slim Fit Polo Shirt", "white", "H&M", "$22.99", "Pique cotton polo with ribbed collar and cuffs. A preppy wardrobe essential."),
    ("Regular Fit Linen Shirt", "sand", "H&M", "$34.99", "Relaxed linen shirt with chest pocket. Effortlessly cool for summer occasions."),
    ("Slim Fit Striped T-shirt", "navy/white", "H&M", "$14.99", "Classic Breton stripes on a slim-fit cotton tee. Nautical with modern edge."),
    ("Muscle Fit T-shirt", "black", "H&M", "$11.99", "Muscle-fit silhouette in stretch cotton. Accentuates athletic build."),
    ("Regular Fit Camp Collar Shirt", "ecru", "H&M", "$27.99", "Relaxed camp collar shirt in cotton voile. Resort-ready with a relaxed vibe."),
    ("Slim Fit Turtleneck", "black", "H&M", "$19.99", "Ribbed turtleneck in soft cotton blend. Sleek and versatile across seasons."),
    ("Printed Hawaiian Shirt", "multi", "H&M", "$24.99", "Vibrant floral print on woven fabric. Vacation-ready and full of personality."),
    ("Regular Fit Denim Shirt", "light blue", "H&M", "$32.99", "Classic denim shirt in cotton chambray. Can be worn open as a layer."),
    ("Slim Fit Merino Knit", "navy", "H&M", "$39.99", "Fine-knit merino wool T-shirt. Luxurious feel with smart-casual versatility."),
    ("Regular Fit Waffle Tee", "olive", "H&M", "$16.99", "Waffle-texture cotton tee with slight stretch. Casual texture play."),
    ("Slim Fit Seersucker Shirt", "blue/white", "H&M", "$29.99", "Textured seersucker fabric in a slim-fit cut. Classic summer sophistication."),
    ("Oversized Polo Shirt", "forest green", "H&M", "$24.99", "Dropped-shoulder polo in heavy pique. Contemporary take on a classic."),
    ("Regular Fit Mock Neck Tee", "charcoal", "H&M", "$14.99", "Minimalist mock neck in smooth jersey. Elevates even the simplest outfit."),
    ("ASOS Slim Fit T-shirt", "white", "ASOS", "$14.00", "Super-soft jersey tee in slim fit. Everyday essential done right."),
    ("ASOS Oversized Tee", "black", "ASOS", "$18.00", "Oversized drop-shoulder tee in cotton jersey. Casual and effortless."),
    ("ASOS Resort Shirt", "blue floral", "ASOS", "$32.00", "Short-sleeve shirt in woven fabric with all-over floral print."),
    ("ASOS Skinny Fit Polo", "navy", "ASOS", "$22.00", "Pique polo in skinny fit. Smart-casual staple with ribbed trims."),
    ("ASOS Linen-blend Shirt", "ecru", "ASOS", "$36.00", "Relaxed linen-blend shirt with minimal detailing. Breathable and refined."),
    ("ASOS Henley Top", "grey marl", "ASOS", "$20.00", "Soft jersey henley with on-trend colour. Easy-wear comfort."),
    ("ASOS Muscle Fit Tee", "white", "ASOS", "$14.00", "Cut to accentuate a strong physique in cotton jersey."),
    ("ASOS Hawaiian Shirt", "palm print", "ASOS", "$28.00", "Revere-collar shirt in all-over palm print. Vacation essential."),
    ("ASOS Striped Tee", "navy/white", "ASOS", "$18.00", "Nautical stripe on slim-fit jersey tee. Preppy and polished."),
    ("ASOS Ribbed T-shirt", "sage green", "ASOS", "$16.00", "Ribbed jersey tee in on-trend colour. Adds subtle texture."),
    ("ASOS Textured Polo", "stone", "ASOS", "$24.00", "Waffle-texture polo in premium cotton. Refined casual wear."),
    ("ASOS Oxford Shirt", "white", "ASOS", "$34.00", "Classic Oxford weave in a relaxed fit. The ultimate smart-casual shirt."),
    ("ASOS Camp Collar Shirt", "khaki", "ASOS", "$30.00", "Relaxed camp collar in cotton twill. Weekend ready."),
    ("ASOS Seersucker Shirt", "sky blue", "ASOS", "$28.00", "Classic seersucker texture in pale blue. Summer sophistication."),
    ("ASOS Mock Neck Tee", "black", "ASOS", "$16.00", "Minimal mock neck in smooth stretch jersey."),
    ("Regular Fit Chambray Shirt", "mid blue", "H&M", "$27.99", "Soft chambray with washed finish. Dressed down or layered up."),
    ("Slim Fit Performance Tee", "black", "H&M", "$17.99", "Moisture-wicking stretch fabric in a slim silhouette. Active meets smart."),
    ("Regular Fit Poplin Shirt", "white", "H&M", "$24.99", "Crisp poplin weave with a clean cut. The foundation of any wardrobe."),
    ("Relaxed Fit Slub Tee", "off-white", "H&M", "$13.99", "Slub-textured cotton with natural variations. Effortless casual texture."),
    ("Slim Fit Floral Shirt", "navy floral", "H&M", "$29.99", "Delicate floral print on deep navy ground. Elegant vacation wear."),
    ("ASOS Slim Fit Oxford", "blue", "ASOS", "$32.00", "Oxford weave shirt in slim silhouette. Sharp weekend staple."),
    ("ASOS Floral Resort Shirt", "white floral", "ASOS", "$30.00", "Light woven fabric with bold floral print. Resort-ready style."),
    ("ASOS Ribbed Polo", "burgundy", "ASOS", "$26.00", "Ribbed polo in rich jewel tone. Adds depth to any casual outfit."),
    ("ASOS Premium Linen Shirt", "white", "ASOS", "$44.00", "100% linen relaxed shirt. Elevated beach-to-bar dressing."),
    ("ASOS Performance Polo", "navy", "ASOS", "$28.00", "Tech-fabric polo with moisture management. Active sophistication."),
    ("Regular Fit Knitted Polo", "camel", "H&M", "$32.99", "Fine-knit polo in luxurious camel tone. Smart-casual at its finest."),
    ("Slim Fit Cotton Blend Tee", "sage", "H&M", "$12.99", "Soft cotton-poly blend tee in muted sage. Easy on the eye, easier to style."),
    ("Regular Fit Mandarin Collar Shirt", "white", "H&M", "$27.99", "Mandarin collar shirt in crisp cotton. Minimal and architectural."),
    ("Slim Fit Thermal Henley", "navy", "H&M", "$19.99", "Waffle-knit thermal henley. Layering essential with refined edge."),
    ("ASOS Textured Tee", "khaki", "ASOS", "$18.00", "Textured jacquard T-shirt. Surface interest without effort."),
    ("ASOS Printed T-shirt", "white", "ASOS", "$20.00", "Bold graphic tee in cotton jersey. Statement piece for casual looks."),
    ("Regular Fit Quarter Zip", "grey", "H&M", "$34.99", "Soft-touch sweatshirt with quarter zip. Weekend sophistication."),
    ("Slim Fit Resort Polo", "sky blue", "H&M", "$22.99", "Lightweight pique polo in cool blue. Yacht-club approved."),
    ("ASOS Slim Polo", "white", "ASOS", "$22.00", "Classic white polo in slim fit pique. Timeless and versatile."),
    ("ASOS Washed Tee", "faded black", "ASOS", "$16.00", "Vintage-washed cotton tee. Broken-in feel from day one."),
    ("Regular Fit Lyocell Shirt", "light mint", "H&M", "$32.99", "Lyocell fabric drapes beautifully. Silky hand-feel with eco credentials."),
    ("Slim Fit Jacquard Polo", "white/navy", "H&M", "$28.99", "Jacquard-knit polo with tonal pattern. Texture and prep combined."),
    ("ASOS Jacquard Polo", "olive", "ASOS", "$30.00", "Tonal jacquard pattern on premium polo. Subtle detail, big impact."),
    ("ASOS Slim Fit Henley", "navy", "ASOS", "$22.00", "Classic henley in slim-fit jersey. Understated and clean."),
    ("Slim Fit Tencel Shirt", "light blue", "H&M", "$29.99", "Sustainable Tencel fabric in slim cut. Soft, breathable and refined."),
    ("Regular Fit Printed Camp Shirt", "tropical print", "H&M", "$27.99", "Bold tropical print on breezy camp collar. Holiday energy year-round."),
    ("ASOS Slim Fit Camp Shirt", "navy floral", "ASOS", "$32.00", "Floral print camp-collar in woven fabric. Resort-ready."),
    ("Regular Fit Band Collar Shirt", "white", "H&M", "$26.99", "Clean band collar in crisp cotton. Minimalist and elevated."),
    ("ASOS Oversized Shirt", "ecru", "ASOS", "$34.00", "Oversized relaxed shirt in cotton poplin. Worn open or buttoned."),
    ("Slim Fit Suede-effect Shirt", "tan", "H&M", "$37.99", "Soft suede-effect fabric in warm tan. Adds luxurious texture to any look."),
    ("ASOS Premium Pique Polo", "sky blue", "ASOS", "$36.00", "Premium heavyweight pique in classic silhouette. Investment casual piece."),
]

_BOTTOMS = [
    ("Slim Fit Chinos", "navy", "H&M", "$29.99", "Classic slim-fit chinos in stretch cotton. Clean lines for polished casual looks."),
    ("Regular Fit Cargo Pants", "khaki", "H&M", "$39.99", "Functional cargo pants with multiple pockets. Utility meets style."),
    ("Slim Fit Trousers", "black", "H&M", "$34.99", "Tailored slim-fit trousers in woven fabric. Versatile from desk to dinner."),
    ("Regular Fit Linen Pants", "sand", "H&M", "$34.99", "Relaxed linen trousers with drawstring waist. Effortless summer style."),
    ("Slim Fit Jeans", "dark blue", "H&M", "$39.99", "Slim-fit jeans in rigid dark denim. A wardrobe cornerstone."),
    ("Regular Fit Shorts", "khaki", "H&M", "$24.99", "Chino-style shorts in stretch cotton. Smart-casual summer essential."),
    ("Slim Fit Suit Trousers", "grey", "H&M", "$44.99", "Slim-fit dress trousers in woven fabric. Elevated office-to-event dressing."),
    ("Loose Fit Linen Shorts", "ecru", "H&M", "$22.99", "Relaxed linen-blend shorts. Beach-to-bar summer versatility."),
    ("Slim Fit Chinos", "olive", "H&M", "$29.99", "Versatile olive chinos with a clean finish. Pairs with almost everything."),
    ("Regular Fit Joggers", "grey", "H&M", "$27.99", "Soft cotton joggers with tapered leg. Elevated loungewear."),
    ("Slim Fit Trousers", "beige", "H&M", "$34.99", "Tailored trousers in warm beige. Smart enough for most occasions."),
    ("Regular Fit Cargo Shorts", "olive", "H&M", "$29.99", "Relaxed cargo shorts with side pockets. Casual summer staple."),
    ("Slim Fit Denim Shorts", "light blue", "H&M", "$27.99", "Slim-cut denim shorts. Weekend wardrobe backbone."),
    ("Regular Fit Twill Trousers", "navy", "H&M", "$37.99", "Crisp cotton twill in a relaxed cut. Polished without effort."),
    ("Slim Fit Cropped Trousers", "tan", "H&M", "$34.99", "Ankle-grazing slim trousers. Contemporary cut for modern dressing."),
    ("Regular Fit Swim Shorts", "blue tropical", "H&M", "$19.99", "Quick-dry swim shorts with vibrant print. Pool to promenade."),
    ("Slim Fit Corduroy Pants", "brown", "H&M", "$39.99", "Fine-wale corduroy in slim silhouette. Texture-rich autumnal staple."),
    ("Regular Fit Chino Shorts", "beige", "H&M", "$22.99", "Clean chino shorts in soft cotton. Versatile warm-weather essential."),
    ("Slim Fit Wool-blend Trousers", "charcoal", "H&M", "$49.99", "Slim trousers in a soft wool blend. Polished and professional."),
    ("Relaxed Fit Linen Trousers", "white", "H&M", "$37.99", "Wide-leg linen trousers in crisp white. Coastal sophistication."),
    ("ASOS Slim Fit Chinos", "stone", "ASOS", "$32.00", "Slim chinos in stretch cotton blend. Versatile smart-casual option."),
    ("ASOS Skinny Jeans", "black", "ASOS", "$38.00", "Super-skinny jeans in black stretch denim. Sharp and edgy."),
    ("ASOS Cargo Pants", "khaki", "ASOS", "$44.00", "Relaxed-fit cargo trousers with utility pockets. Fashion-forward functionality."),
    ("ASOS Smart Trousers", "navy", "ASOS", "$46.00", "Tailored smart trousers in woven fabric. Business-casual confidence."),
    ("ASOS Linen Pants", "ecru", "ASOS", "$40.00", "Relaxed linen blend trousers. Holiday-ready ease."),
    ("ASOS Chino Shorts", "mid wash", "ASOS", "$28.00", "Classic chino shorts in denim fabric. Summer staple."),
    ("ASOS Wide Leg Trousers", "beige", "ASOS", "$48.00", "Contemporary wide-leg cut in woven fabric. Statement tailoring."),
    ("ASOS Swim Shorts", "navy tropical", "ASOS", "$24.00", "Tropical print swim shorts. Bold holiday energy."),
    ("ASOS Slim Fit Chinos", "navy", "ASOS", "$32.00", "Slim-cut chinos in stretch cotton. Clean and polished."),
    ("ASOS Relaxed Joggers", "grey", "ASOS", "$36.00", "Tapered joggers in soft jersey. Refined casual comfort."),
    ("ASOS Cropped Trousers", "black", "ASOS", "$40.00", "Cropped tailored trousers. Modern slim silhouette."),
    ("ASOS Denim Shorts", "dark wash", "ASOS", "$32.00", "Mid-thigh denim shorts in dark wash. Versatile summer piece."),
    ("ASOS Linen Shorts", "sand", "ASOS", "$30.00", "Easy linen shorts with elastic waist. Cool and breezy."),
    ("ASOS Twill Trousers", "olive", "ASOS", "$42.00", "Relaxed twill trousers with front pleats. Relaxed refinement."),
    ("ASOS Corduroy Trousers", "tan", "ASOS", "$44.00", "Fine-cord trousers in warm tan. Textured smart-casual."),
    ("Regular Fit Pleated Trousers", "beige", "H&M", "$44.99", "Pleated front trousers in woven fabric. Timeless tailoring."),
    ("Slim Fit Tech Pants", "black", "H&M", "$49.99", "Performance-stretch tech fabric in tailored cut. Modern and functional."),
    ("Regular Fit Drawstring Shorts", "navy", "H&M", "$19.99", "Lightweight drawstring shorts in quick-dry fabric. Active-casual versatility."),
    ("Slim Fit Linen Shorts", "olive", "H&M", "$24.99", "Tailored linen shorts with a slim leg. Summer sophistication."),
    ("Regular Fit Paisley Swim Shorts", "navy paisley", "H&M", "$22.99", "Paisley-printed swim shorts in quick-dry fabric. Refined resort wear."),
    ("ASOS Slim Fit Wool Trousers", "grey", "ASOS", "$58.00", "Slim-fit trousers in a soft wool blend. Elevated office dressing."),
    ("ASOS Linen Blend Shorts", "ecru", "ASOS", "$28.00", "Linen-blend shorts with a relaxed fit. Effortless summer casual."),
    ("ASOS Pleated Chinos", "camel", "ASOS", "$44.00", "Pleated front chinos in cotton twill. Relaxed tailoring with personality."),
    ("ASOS Straight Leg Jeans", "light blue", "ASOS", "$42.00", "Classic straight-leg jeans in mid-wash denim. The ultimate denim basic."),
    ("Regular Fit Jogging Bottoms", "olive", "H&M", "$29.99", "Tapered joggers in soft cotton. Weekend-ready comfort."),
    ("Slim Fit Cotton Trousers", "white", "H&M", "$37.99", "Clean white trousers in stretch cotton. Bold summer statement."),
    ("ASOS Smart Shorts", "navy", "ASOS", "$30.00", "Tailored smart shorts above the knee. Dressed-up summer dressing."),
    ("ASOS Slim Linen Shorts", "white", "ASOS", "$26.00", "Slim-fit linen shorts in clean white. Resort sophistication."),
    ("Regular Fit Nylon Shorts", "black", "H&M", "$22.99", "Lightweight nylon shorts. Active styling with sleek finish."),
    ("Slim Fit Sateen Trousers", "navy", "H&M", "$44.99", "Slim sateen-finish trousers. Subtle sheen for evening occasions."),
    ("ASOS Sateen Trousers", "black", "ASOS", "$52.00", "Sateen finish smart trousers. Understated luxury."),
    ("Regular Fit Relaxed Chinos", "stone", "H&M", "$32.99", "Relaxed-cut chinos with tapered ankle. Polished yet comfortable."),
    ("ASOS Tapered Chinos", "olive", "ASOS", "$38.00", "Tapered chinos in stretch cotton. Slim from knee to ankle."),
    ("Slim Fit Jeans", "indigo", "H&M", "$42.99", "Mid-indigo slim jeans in rigid denim. A versatile blue denim."),
    ("Regular Fit Checked Shorts", "blue check", "H&M", "$24.99", "Woven checked pattern shorts. Preppy summer character."),
    ("ASOS Checked Shorts", "khaki check", "ASOS", "$28.00", "Smart checked pattern shorts. Country-casual energy."),
    ("Regular Fit Belted Chinos", "camel", "H&M", "$37.99", "Belted chinos in warm camel. Sharp silhouette with character."),
    ("ASOS Straight Leg Chinos", "beige", "ASOS", "$36.00", "Straight-cut chinos in stretch cotton. Clean and versatile."),
    ("Slim Fit Jeans", "light blue", "H&M", "$39.99", "Light-wash slim jeans in cotton denim. Classic denim refined."),
    ("ASOS Wide Leg Jeans", "black", "ASOS", "$48.00", "Wide-leg jeans in black denim. Statement casual."),
    ("Regular Fit Pull-on Trousers", "grey", "H&M", "$34.99", "Elasticated waist trousers in woven fabric. Comfort without compromise."),
    ("ASOS Tapered Trousers", "sand", "ASOS", "$44.00", "Tapered fit trousers in warm sand. Smart-casual at its best."),
    ("Regular Fit Printed Shorts", "hawaiian print", "H&M", "$22.99", "Bold tropical print on casual shorts. Holiday personality."),
    ("ASOS Printed Shorts", "navy print", "ASOS", "$26.00", "Graphic printed shorts for vacation days."),
    ("Slim Fit Pintuck Trousers", "black", "H&M", "$44.99", "Pintuck detail on tailored slim trousers. Minimal but sophisticated."),
    ("ASOS Slim Cargo Trousers", "black", "ASOS", "$52.00", "Slim-fit cargo trousers in technical fabric. Elevated utility."),
]


def generate_mock_catalog() -> list[dict]:
    items = []
    for i, (name, color, source, price, desc) in enumerate(_TOPS):
        items.append({
            "id": f"mock_top_{i+1:03d}",
            "name": name,
            "price": price,
            "image_url": f"https://picsum.photos/seed/top{i+1}/400/500",
            "category": "tops",
            "description": desc,
            "color": color,
            "source": source,
            "url": f"https://{'hm' if source=='H&M' else 'asos'}.com/product/top-{i+1}",
        })
    for i, (name, color, source, price, desc) in enumerate(_BOTTOMS):
        items.append({
            "id": f"mock_bottom_{i+1:03d}",
            "name": name,
            "price": price,
            "image_url": f"https://picsum.photos/seed/bottom{i+1}/400/500",
            "category": "bottoms",
            "description": desc,
            "color": color,
            "source": source,
            "url": f"https://{'hm' if source=='H&M' else 'asos'}.com/product/bottom-{i+1}",
        })
    return items
